-- Author: TTG
-- Description: Create FRIEND_REQUEST table
------------------------------------------------------------------------------------------------------------------------

CREATE SEQUENCE IF NOT EXISTS product.FRIEND_REQUEST_SEQ
    START WITH 1
    INCREMENT BY 50
    NO MAXVALUE
    NO CYCLE;

CREATE TABLE IF NOT EXISTS product.FRIEND_REQUEST (
    FRIEND_REQUEST_ID       INTEGER                         NOT NULL,
    FROM_USER_ID            INTEGER                         NOT NULL,
    TO_USER_ID              INTEGER                         NOT NULL,
    STATUS                  VARCHAR(20)                     NOT NULL,
    MESSAGE                 VARCHAR(500),
    USR_CREATION            VARCHAR(128)                    NOT NULL,
    DTE_CREATION            TIMESTAMP WITH TIME ZONE        NOT NULL,
    USR_LAST_MODIFICATION   VARCHAR(128)                    NOT NULL,
    DTE_LAST_MODIFICATION   TIMESTAMP WITH TIME ZONE        NOT NULL,
    VERSION                 INTEGER                         NOT NULL,

    CONSTRAINT PK_FRIEND_REQUEST PRIMARY KEY (FRIEND_REQUEST_ID),

    CONSTRAINT FK_FRIEND_REQUEST_FROM_USER FOREIGN KEY (FROM_USER_ID)
        REFERENCES product.USER(USER_ID),
    CONSTRAINT FK_FRIEND_REQUEST_TO_USER FOREIGN KEY (TO_USER_ID)
        REFERENCES product.USER(USER_ID),

    CONSTRAINT CKC_FRIEND_REQUEST_STATUS CHECK (STATUS IN ('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED'))
);

ALTER SEQUENCE product.FRIEND_REQUEST_SEQ OWNED BY product.FRIEND_REQUEST.FRIEND_REQUEST_ID;

CREATE INDEX IF NOT EXISTS IDX_FRIEND_REQUEST_FROM_USER ON product.FRIEND_REQUEST(FROM_USER_ID);
CREATE INDEX IF NOT EXISTS IDX_FRIEND_REQUEST_TO_USER ON product.FRIEND_REQUEST(TO_USER_ID);