-- Author: TTG
-- Description: Create FRIEND_RELATIONSHIP table
------------------------------------------------------------------------------------------------------------------------

CREATE SEQUENCE IF NOT EXISTS product.FRIEND_RELATIONSHIP_SEQ
    START WITH 1
    INCREMENT BY 50
    NO MAXVALUE
    NO CYCLE;

CREATE TABLE IF NOT EXISTS product.FRIEND_RELATIONSHIP (
    FRIEND_RELATIONSHIP_ID      INTEGER                         NOT NULL,

    FIRST_USER_ID               INTEGER                         NOT NULL,
    SECOND_USER_ID              INTEGER                         NOT NULL,
    FRIEND_REQUEST_ID           INTEGER,
    STATUS                      VARCHAR(20)                     NOT NULL,
    USR_CREATION                VARCHAR(128)                    NOT NULL,
    DTE_CREATION                TIMESTAMP WITH TIME ZONE        NOT NULL,
    USR_LAST_MODIFICATION       VARCHAR(128)                    NOT NULL,
    DTE_LAST_MODIFICATION       TIMESTAMP WITH TIME ZONE        NOT NULL,
    VERSION                     INTEGER                         NOT NULL,
    
    CONSTRAINT PK_FRIEND_RELATIONSHIP PRIMARY KEY (FRIEND_RELATIONSHIP_ID),
    
    CONSTRAINT FK_FRIEND_RELATIONSHIP_USER1 FOREIGN KEY (FIRST_USER_ID)
        REFERENCES product.USER (USER_ID),
    CONSTRAINT FK_FRIEND_RELATIONSHIP_USER2 FOREIGN KEY (SECOND_USER_ID) 
        REFERENCES product.USER (USER_ID),
    CONSTRAINT FK_FRIEND_RELATIONSHIP_REQUEST FOREIGN KEY (FRIEND_REQUEST_ID) 
        REFERENCES product.FRIEND_REQUEST(FRIEND_REQUEST_ID),
    
    CONSTRAINT CKC_FRIEND_RELATIONSHIP_STATUS CHECK (STATUS IN ('ACTIVE', 'BLOCKED', 'DELETED'))
);

ALTER SEQUENCE product.FRIEND_RELATIONSHIP_SEQ OWNED BY product.FRIEND_RELATIONSHIP.FRIEND_RELATIONSHIP_ID;

CREATE INDEX IF NOT EXISTS IDX_FRIEND_RELATIONSHIP_FIRST_USER_ID ON product.FRIEND_RELATIONSHIP(FIRST_USER_ID);
CREATE INDEX IF NOT EXISTS IDX_FRIEND_RELATIONSHIP_SECOND_USER_ID ON product.FRIEND_RELATIONSHIP(SECOND_USER_ID);